site_name: "Portfolio"
theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.indexes
  palette:
    - scheme: slate
      primary: "#1A237E"
      accent: "#4FC3F7"
  icon:
    logo: material/flower-tulip
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - monorepo
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - css/extra.css

nav:
  - Pagina Principal:
    - Inicio: index.md
    - 'Acerca de mí': acerca.md
    - Portfolio: portfolio/index.md
    - Recursos: recursos.md
  - 'Ingeniería de Datos': "!include ./idd/mkdocs.yml"