# Archivo: data-eng/mkdocs.yml

# Nota: El título principal del navegador seguirá siendo el del archivo global
# Pero puedes definir aquí el tema y la paleta.
site_name: Ingeniería de Datos
site_url: https://avrilabg.github.io/portfolio/ingenieria-de-datos/

theme:
  name: material
  palette:
    - scheme: red
      primary: deep orange
      accent: light green
  features:
    - navigation.sections
    - navigation.indexes

plugins: 
- awesome-pages
