# Archivo: data-eng/mkdocs.yml

# Nota: El título principal del navegador seguirá siendo el del archivo global
# Pero puedes definir aquí el tema y la paleta.
site_name: Ingeniería de Datos
site_url: https://avrilabg.github.io/portfolio/ingenieria-de-datos/

theme:
  name: material
  palette:
    # 1. ESQUEMA DE COLOR: 'light' o 'slate' (oscuro)
    scheme: slate
    # 2. COLOR PRIMARIO (Header, barra lateral)
    primary: deep orange
    # 3. COLOR ACCENTO (Links, botones)
    accent: light green
  features:
    - navigation.sections
    - navigation.indexes
    - navegation.expand

plugins: 
- awesome-pages
